name: Workflow_1

on: [ push, pull_request ]
env:
  pwsh: PowerShell
jobs:
  MyBuild:
    runs-on: self-hosted
    steps:
    - name: setup-actions
      uses: actions/checkout@v3
    - name: Install PowerShell Core
      run: |
        Start-Process -FilePath "powershell" -ArgumentList "-Command", "Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force; Invoke-WebRequest -Uri https://aka.ms/install-powershell.ps1 -OutFile install-powershell.ps1; ./install-powershell.ps1; Remove-Item -Path install-powershell.ps1 -Force"
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1.4
    - name: clang version check
      run: clang++ --version
