name: Workflow_1

on: [ push, pull_request ]
env:
  pwsh: PowerShell
jobs:
  MyBuild:
    runs-on: self-hosted
    steps:
    - name: setup-actions
      uses: actions/checkout@v3
    - name: Install PowerShell Core
      run: |
        & 'C:\Program Files\PowerShell\7\pwsh.exe' -Command "& {&'Invoke-WebRequest' -Uri https://aka.ms/install-powershell.ps1 -UseBasicParsing | & 'Invoke-Expression'}"
    - name: Set up Clang
      run: |
        choco install llvm
    - name: clang version check
      run: clang++ --version
