name: Modi_Workflow_1

on: [ push, pull_request ]
jobs:
  myBuild:
    runs-on: self-hosted
    steps:
    - name: setup-actions
      uses: actions/checkout@v2
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.7.0
      with:
        platform: "win64"
    - name: clang version check
      run: clang++ --version
