name: Workflow_1

on: [ push, pull_request ]
jobs:
  MyBuild:
    runs-on: self-hosted
    steps:
    - name: setup-actions
      uses: actions/checkout@v3
    - name: Chocolatey Action
      uses: crazy-max/ghaction-chocolatey@v2.1.0
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1.4
      with:
        version: latest
        platform: x64
    - name: clang version check
      run: clang++ --version
