name: Workflow_1

on: [ push, pull_request ]
jobs:
  MyBuild:
    runs-on: self-hosted
    steps:
    - name: setup-actions
      uses: actions/checkout@v2
    - name: Love
      shell: pwsh
      run: echo "LOVE"
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: clang version check
      run: clang++ --version
