name: Workflow_1

on: [ push, pull_request ]
jobs:
  MyBuild:
    runs-on: self-hosted
    steps:
    - name: setup-actions
      uses: actions/checkout@v2
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzVM -ResourceGroupName "ResourceGroup11"
        azPSVersion: "latest"
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: clang version check
      run: clang++ --version
