name: Workflow_1

on: [ push, pull_request ]
jobs:
  MyBuild:
    runs-on: self-hosted
    steps:
    - name: setup-actions
      uses: actions/checkout@v2
    - name: Install powershell-devops Module
      uses: powershell-devops/powershell-devops@v0.2.0
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: clang version check
      run: clang++ --version
