name: Modi_Workflow_1

on: [ push, pull_request ]
jobs:
  myBuild:
    runs-on: self-hosted
    steps:
    - name: setup-actions
      uses: actions/checkout@v2
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1
      with:
          version: 13
    - name: clang version check
      run: clang++ --version
