name: Workflow_1

on: [ push, pull_request ]
env:
  pwsh: PowerShell
jobs:
  MyBuild:
    runs-on: self-hosted
    steps:
    - name: setup-actions
      uses: actions/checkout@v3
    - name: setup-node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name : Istall PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell
    - name: Add PowerShell Core to PATH
      run: |
        echo "export PATH=\$PATH:/usr/bin/pwsh" >> $GITHUB_ENV
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: clang version check
      run: clang++ --version
