name: Workflow_1

on: [ push, pull_request ]
jobs:
  MyBuild:
    runs-on: self-hosted
    steps:
    - name: setup-actions
      uses: actions/checkout@v3
    - name: clang version check
      run: clang++ --version
